name: Build and Deploy Flutter Web

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:

    # Use a Docker container with Flutter SDK to avoid runner setup issues
    runs-on: ubuntu-latest
    container:
      image: docker://cirrusci/flutter:3.10.6
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Build web (in container)
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
